version: "3"
services:
  traefik:
    image: traefik:latest
    command: --web --api --docker --docker.domain=docker.localhost 
    ports:
    - "80:80"
    - "8083:8080"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  server:
    build:
       context: "/home/jeeva/projects/Docker/"
     image: jeevaram97/testing:v.0.0.2
    
    labels:
      - "traefik.backend=server"
      - "traefik.frontend.port=5001"
      - "traefik.frontend.rule=Host:hello.tricogdev.com;PathPrefixStrip:/api"
    volumes:
      - "/home/jeeva/projects/Docker/:/usr/src/app"
    # ports:
    #   - "5001:8000" 
    depends_on:
    - traefik 
  client:
    image: jeevaram97/anotherservice:react.v.0.0.2
    build:
      context: "/home/jeeva/projects/ReactDocker/"
    # ports:
    #   - "8000:80"
    # volumes:
    #   - "/home/jeeva/projects/anotherService/dist:/usr/src/app" 
    #   - "/home/jeeva/projects/anotherService/:/etc/nginx/config.d/default.conf"
    labels:
      - "traefik.backend=client"
      - "traefik.frontend.port=8080"
      - "traefik.frontend.rule=Host:hello;"
    depends_on:
      - traefik
